[workspace]

members = [
    "noir_field",
    "noir_evaluator",
    "noir",
    "aztec_backend",
    "noirc_frontend",
    "noirc_errors",
    "noirc_driver",
    "acir",
    "std_lib",
    "nargo",
]