[workspace]

members = [
    "noir_field",
    "noir_evaluator",
    
    "aztec_backend",
    "pwg",
    "noirc_frontend",
    "noirc_errors",
    "noirc_driver",
    "acir",
    "std_lib",
    "nargo",
    "fm",
    "arena",
    "acvm",
    "noirc_abi"
]