[workspace]

members = [
    "noir_field",
    "libnoirc_lexer",
    "libnoirc_parser",
    "libnoirc_analyser",
    "barretenberg-rs",
    "noir_evaluator",
    "noir_cli",
    "noir_serialiser",
    "noir_wg",
    "low_level_std_lib",
]