[package]
name = "acvm"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acir = {path = "../acir"}

# Ideally, there should be a way for the Nargo.toml file to indicate a proof system
# and not need to pull in the other proof systems. Also ideally like to avoid using DLL
# It seems to be only way... This is not an immediate problem while dependencies are small
aztec_backend = {path = "../aztec_backend"}
noir_field = {path = "../noir_field"}
sha2 = "0.9.3"
# This is only needed for tests. Idealy it should be in dev-dependencies 
# and we should conditionally compile it only for tests.
enum-iterator = "0.6.0" 

[dev-dependencies]