name: Publish
# <arch>-<vendor>-<os>-<env>
# For esoteric targets, there is probably a succint way to do it with a target array
# Alternatively, we can wait for action-rs to get a v2, where we can input 'targets' 

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: noir
            asset_name: noir-linux
            target: x86_64-unknown-linux-gnu
          - name: windows
            os: windows-latest
            artifact_name: noir.exe
            asset_name: noir-windows
            target: x86_64-pc-windows-gnu
          - name: macos
            os: macos-latest
            artifact_name: noir
            asset_name: noir-macos
            target: x86_64-apple-darwin

    steps:
    - uses: actions/checkout@v1

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        # target: ${{ matrix.target }}

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}-${{ steps.previoustag.outputs.tag }}
        tag: ${{ github.ref }}
