name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --exclude aztec_backend
    - name: Run Check
      run: cargo check
      
# Check is needed as we exclude aztec_backend from tests 
# Tests in the Aztec backend, require an SRS which is too big for github.
# They are disabled for now and ran locally.
